on:
  schedule:
    - cron: "* * * * *"

jobs:
 mirror:
  runs-on: ubuntu-latest
  steps:
  - run: env
  - run: uname -a
  - uses: actions/checkout@HEAD
  - run: git push https://github.com/rafaelgieschke/test @:refs/heads/test123
